<!-- Copyright 1999-2016. Parallels IP Holdings GmbH. -->
<a href="<?php echo pm_Context::getActionUrl('document', 'index'); ?>">Documents</a> - Navigation by tabs. 1 title for both tabs (tabbed = true). + Simple page on the same level as tabs.<br><br>

<a href="<?php echo pm_Context::getActionUrl('pet', 'index'); ?>">Pets</a> - Navigation by tabs. Different titles for tabs (tabbed = false).<br><br>

<a href="<?php echo pm_Context::getActionUrl('picture', 'index'); ?>">Pictures</a> - Object switcher.<br><br>
