<?php echo $this->renderTabs($this->tabs); ?>
<b>Docs on  API-RPC:</b><br><br>


<a href="<?php echo pm_Context::getActionUrl('document', 'admin'); ?>">Specify Admin's Password After the Plesk Initialization</a><br><br>

<a href="<?php echo pm_Context::getActionUrl('document', 'client'); ?>">Create a client</a><br><br>

<a href="<?php echo pm_Context::getActionUrl('document', 'subscription'); ?>">Create a subscription</a><br><br>

<a href="<?php echo pm_Context::getActionUrl('document', 'simple'); ?>">Go to simple page in the same level as tabs</a><br><br>